export type Agent = "OpenClaw" | "Nanobot";

export type Domain =
  | "BrowseCompPlus"
  | "OmniMath"
  | "SWE-Bench"
  | "LiveCodeBench"
  | "GDPVal";

// SkillMethod is a string so new methods in leaderboard.csv don't require code changes.
export type SkillMethod = string;

export interface LeaderboardEntry {
  agent: Agent;
  model: string;
  domain: Domain;
  skillMethod: SkillMethod;
  without: number;
  withSkills: number;
  cost: string;
}

export const AGENTS: Agent[] = ["OpenClaw", "Nanobot"];

export const DOMAINS: Domain[] = [
  "BrowseCompPlus",
  "OmniMath",
  "SWE-Bench",
  "LiveCodeBench",
  "GDPVal",
];

// Auto-regenerated by scripts/csv-to-data.js from unique skillMethod values in the CSV.
export const SKILL_METHODS: SkillMethod[] = ["EverOS", "Memento", "ReasoningBank", "Human Design", "EvoSkill", "OpenSpace", "GEPA"];

export const AGENT_COLORS: Record<Agent, string> = {
  OpenClaw: "#ef4444",
  Nanobot: "#3b82f6",
};

export const AGENT_BAR_COLORS: Record<Agent, string> = {
  OpenClaw: "#c2703a",
  Nanobot: "#6366f1",
};

export const DOMAIN_LABELS: Record<Domain, string> = {
  BrowseCompPlus: "Information Retrieval",
  OmniMath: "Reasoning & Problem Decomposition",
  "SWE-Bench": "Software Engineering",
  LiveCodeBench: "Code Implementation",
  GDPVal: "Knowledge Work",
};

export const DOMAIN_TAG_COLORS: Record<Domain, { bg: string; text: string }> = {
  BrowseCompPlus: { bg: "#fde68a", text: "#78350f" },
  OmniMath: { bg: "#dbeafe", text: "#1e40af" },
  "SWE-Bench": { bg: "#fce7f3", text: "#9d174d" },
  LiveCodeBench: { bg: "#d1fae5", text: "#065f46" },
  GDPVal: { bg: "#ede9fe", text: "#5b21b6" },
};

// Fallback palette cycles through these colors for any skill method not in the explicit map.
const SKILL_METHOD_PALETTE: Array<{ bg: string; text: string }> = [
  { bg: "#d1fae5", text: "#065f46" },
  { bg: "#e0f2fe", text: "#0369a1" },
  { bg: "#fce7f3", text: "#9d174d" },
  { bg: "#fef3c7", text: "#92400e" },
  { bg: "#ede9fe", text: "#5b21b6" },
  { bg: "#fef9c3", text: "#713f12" },
];

const EXPLICIT_METHOD_COLORS: Record<string, { bg: string; text: string }> = {
  EverOS: { bg: "#d1fae5", text: "#065f46" },
  "Human Design": { bg: "#e0f2fe", text: "#0369a1" },
};

export const SKILL_METHOD_TAG_COLORS: Record<string, { bg: string; text: string }> = new Proxy(
  EXPLICIT_METHOD_COLORS,
  {
    get(target, prop: string) {
      if (prop in target) return target[prop];
      // Deterministic hash-based color for unknown methods.
      let h = 0;
      for (let i = 0; i < prop.length; i++) h = (h * 31 + prop.charCodeAt(i)) >>> 0;
      return SKILL_METHOD_PALETTE[h % SKILL_METHOD_PALETTE.length];
    },
  }
);

// --- Domain descriptions (from README) ---

export interface DomainInfo {
  id: Domain;
  name: string;
  baseBenchmark: string;
  category: string;
  description: string;
  clusters: string;
  train: number;
  test: number;
  docker: boolean;
}

export const DOMAIN_INFO: DomainInfo[] = [
  {
    id: "BrowseCompPlus",
    name: "Information Retrieval",
    baseBenchmark: "BrowseCompPlus",
    category: "Information Retrieval",
    description: "Search a local corpus to answer complex multi-constraint questions.",
    clusters: "10 (by topic)",
    train: 154,
    test: 65,
    docker: false,
  },
  {
    id: "OmniMath",
    name: "Reasoning & Problem Decomposition",
    baseBenchmark: "OmniMath",
    category: "Reasoning",
    description: "Solve competition-level math problems across multiple subdisciplines.",
    clusters: "By subdiscipline",
    train: 478,
    test: 100,
    docker: false,
  },
  {
    id: "SWE-Bench",
    name: "Software Engineering",
    baseBenchmark: "SWE-Bench",
    category: "Software Engineering",
    description: "Fix real-world bugs in open-source Python repositories.",
    clusters: "19 (by repo)",
    train: 101,
    test: 26,
    docker: true,
  },
  {
    id: "LiveCodeBench",
    name: "Code Implementation",
    baseBenchmark: "LiveCodeBench",
    category: "Code Implementation",
    description: "Solve competitive programming problems with code execution.",
    clusters: "39 (by type)",
    train: 97,
    test: 39,
    docker: false,
  },
  {
    id: "GDPVal",
    name: "Knowledge Work",
    baseBenchmark: "GDPVal",
    category: "Knowledge Work",
    description: "Perform real-world occupational tasks (Excel, PDF, Word).",
    clusters: "29 (by occupation)",
    train: 87,
    test: 58,
    docker: false,
  },
];

// --- Skill method descriptions ---

export interface AllMethodInfo {
  name: string;
  description: string;
  approach: string;
  github: string;
  status: "available" | "coming_soon";
}

export const ALL_METHODS: AllMethodInfo[] = [
  {
    name: "EverOS",
    description: "A memory OS that makes agents more personal while saving tokens. Extracts and stores long-term memory from session trajectories, then injects reusable skills as domain-specific strategies.",
    approach: "Memory-based extraction",
    github: "https://github.com/EverMind-AI/EverOS",
    status: "available",
  },
  {
    name: "EvoSkill",
    description: "An agent-agnostic toolkit for automatically creating and improving AI skills. Runs an evolution loop where an Executor collects failures and a Proposer analyzes patterns to synthesize reusable skills.",
    approach: "Evolutionary optimization",
    github: "https://github.com/sentient-agi/EvoSkill",
    status: "available",
  },
  {
    name: "Memento",
    description: "A memory-based continual-learning framework using Case-Based Reasoning. Logs successful and failed trajectories into a Case Bank, retrieves by Q-value with SimCSE embeddings to steer planning.",
    approach: "Retrieval-based (CBR)",
    github: "https://github.com/Agent-on-the-Fly/Memento",
    status: "available",
  },
  {
    name: "OpenSpace",
    description: "A self-evolving engine where every task makes every agent smarter. Skills automatically select, apply, monitor, analyze, and evolve themselves via three evolution modes (FIX, DERIVED, CAPTURED).",
    approach: "Continuous accumulation",
    github: "https://github.com/HKUDS/OpenSpace",
    status: "available",
  },
  {
    name: "ReasoningBank",
    description: "A memory mechanism that learns from both successful and failed trajectories, storing reasoning as memory content. Introduces memory-aware test-time scaling — experience-driven memory as an additional scaling dimension for agent systems.",
    approach: "Memory + reasoning",
    github: "https://github.com/google-research/reasoning-bank",
    status: "available",
  },
];

// --- Leaderboard data (real results from OpenClaw experiments) ---
// Only domains with actual experiment data are included

export const leaderboardData: LeaderboardEntry[] = [
  { agent: "OpenClaw", model: "Qwen3.5-397B", domain: "BrowseCompPlus", skillMethod: "EverOS", without: 40, withSkills: 33.8, cost: "↓ 20.4% turns" },
  { agent: "OpenClaw", model: "Qwen3.5-27B", domain: "BrowseCompPlus", skillMethod: "EverOS", without: 10.8, withSkills: 9.2, cost: "↓ 8.4% turns" },
  { agent: "OpenClaw", model: "Qwen3.5-397B", domain: "BrowseCompPlus", skillMethod: "Memento", without: 40, withSkills: 60, cost: "↓ 13.1% turns" },
  { agent: "OpenClaw", model: "Qwen3.5-27B", domain: "BrowseCompPlus", skillMethod: "Memento", without: 10.8, withSkills: 7.7, cost: "↑ 53.4% turns" },
  { agent: "OpenClaw", model: "Qwen3.5-397B", domain: "BrowseCompPlus", skillMethod: "ReasoningBank", without: 40, withSkills: 49.2, cost: "↓ 12.9% turns" },
  { agent: "OpenClaw", model: "Qwen3.5-397B", domain: "BrowseCompPlus", skillMethod: "Human Design", without: 40, withSkills: 64.6, cost: "↓ 38.7% turns" },
  { agent: "OpenClaw", model: "Qwen3.5-27B", domain: "BrowseCompPlus", skillMethod: "Human Design", without: 10.8, withSkills: 13.8, cost: "↓ 30.6% turns" },
  { agent: "OpenClaw", model: "Qwen3.5-397B", domain: "BrowseCompPlus", skillMethod: "EvoSkill", without: 40, withSkills: 43.1, cost: "↓ 19.6% turns" },
  { agent: "OpenClaw", model: "Qwen3.5-27B", domain: "BrowseCompPlus", skillMethod: "EvoSkill", without: 10.8, withSkills: 7.7, cost: "— 0% turns" },
  { agent: "OpenClaw", model: "Qwen3.5-397B", domain: "BrowseCompPlus", skillMethod: "OpenSpace", without: 40, withSkills: 49.2, cost: "↑ 57.9% turns" },
  { agent: "OpenClaw", model: "Qwen3.5-27B", domain: "BrowseCompPlus", skillMethod: "OpenSpace", without: 10.8, withSkills: 27.7, cost: "↑ 54.0% turns" },
  { agent: "OpenClaw", model: "Qwen3.5-397B", domain: "SWE-Bench", skillMethod: "EverOS", without: 34.6, withSkills: 50, cost: "↓ 21.4% turns" },
  { agent: "OpenClaw", model: "Qwen3.5-27B", domain: "SWE-Bench", skillMethod: "EverOS", without: 42.3, withSkills: 50, cost: "↓ 1.5% turns" },
  { agent: "OpenClaw", model: "Qwen3.5-397B", domain: "SWE-Bench", skillMethod: "Memento", without: 34.6, withSkills: 37.5, cost: "↓ 0.2% turns" },
  { agent: "OpenClaw", model: "Qwen3.5-27B", domain: "SWE-Bench", skillMethod: "Memento", without: 42.3, withSkills: 45.8, cost: "↑ 11.7% turns" },
  { agent: "OpenClaw", model: "Qwen3.5-397B", domain: "SWE-Bench", skillMethod: "ReasoningBank", without: 34.6, withSkills: 26.9, cost: "↑ 21.3% turns" },
  { agent: "OpenClaw", model: "Qwen3.5-397B", domain: "SWE-Bench", skillMethod: "Human Design", without: 34.6, withSkills: 38.5, cost: "↑ 0.3% turns" },
  { agent: "OpenClaw", model: "Qwen3.5-27B", domain: "SWE-Bench", skillMethod: "Human Design", without: 42.3, withSkills: 42.3, cost: "↑ 1.6% turns" },
  { agent: "OpenClaw", model: "Qwen3.5-397B", domain: "SWE-Bench", skillMethod: "EvoSkill", without: 34.6, withSkills: 46.2, cost: "↑ 25.8% turns" },
  { agent: "OpenClaw", model: "Qwen3.5-27B", domain: "SWE-Bench", skillMethod: "EvoSkill", without: 42.3, withSkills: 38.5, cost: "↑ 94.9% turns" },
  { agent: "OpenClaw", model: "Qwen3.5-397B", domain: "SWE-Bench", skillMethod: "OpenSpace", without: 34.6, withSkills: 51.7, cost: "↑ 22.1% turns" },
  { agent: "OpenClaw", model: "Qwen3.5-27B", domain: "SWE-Bench", skillMethod: "OpenSpace", without: 42.3, withSkills: 37.9, cost: "↑ 60.8% turns" },
  { agent: "OpenClaw", model: "Qwen3.5-397B", domain: "OmniMath", skillMethod: "EverOS", without: 48, withSkills: 50, cost: "↓ 18.0% chars" },
  { agent: "OpenClaw", model: "Qwen3.5-27B", domain: "OmniMath", skillMethod: "EverOS", without: 44, withSkills: 39, cost: "↓ 31.8% chars" },
  { agent: "OpenClaw", model: "Qwen3.5-397B", domain: "OmniMath", skillMethod: "Memento", without: 48, withSkills: 38, cost: "↑ 68.5% chars" },
  { agent: "OpenClaw", model: "Qwen3.5-27B", domain: "OmniMath", skillMethod: "Memento", without: 44, withSkills: 32, cost: "↑ 21.1% chars" },
  { agent: "OpenClaw", model: "Qwen3.5-397B", domain: "OmniMath", skillMethod: "ReasoningBank", without: 48, withSkills: 43, cost: "↓ 13.8% chars" },
  { agent: "OpenClaw", model: "Qwen3.5-397B", domain: "OmniMath", skillMethod: "Human Design", without: 48, withSkills: 60, cost: "↑ 2.7% chars" },
  { agent: "OpenClaw", model: "Qwen3.5-27B", domain: "OmniMath", skillMethod: "Human Design", without: 44, withSkills: 29, cost: "↓ 13.0% chars" },
  { agent: "OpenClaw", model: "Qwen3.5-397B", domain: "OmniMath", skillMethod: "EvoSkill", without: 48, withSkills: 56, cost: "↓ 28.7% chars" },
  { agent: "OpenClaw", model: "Qwen3.5-27B", domain: "OmniMath", skillMethod: "EvoSkill", without: 44, withSkills: 34, cost: "↓ 6.3% chars" },
  { agent: "OpenClaw", model: "Qwen3.5-397B", domain: "OmniMath", skillMethod: "OpenSpace", without: 48, withSkills: 49, cost: "↑ 5.2% chars" },
  { agent: "OpenClaw", model: "Qwen3.5-27B", domain: "OmniMath", skillMethod: "OpenSpace", without: 44, withSkills: 39, cost: "↓ 13.2% chars" },
  { agent: "OpenClaw", model: "Qwen3.5-397B", domain: "GDPVal", skillMethod: "EverOS", without: 51.7, withSkills: 53.4, cost: "↑ 4.4% turns" },
  { agent: "OpenClaw", model: "Qwen3.5-27B", domain: "GDPVal", skillMethod: "EverOS", without: 46.6, withSkills: 50, cost: "↑ 5.5% turns" },
  { agent: "OpenClaw", model: "Qwen3.5-397B", domain: "GDPVal", skillMethod: "Memento", without: 51.7, withSkills: 62.1, cost: "↑ 7.5% turns" },
  { agent: "OpenClaw", model: "Qwen3.5-27B", domain: "GDPVal", skillMethod: "Memento", without: 46.6, withSkills: 58.6, cost: "↓ 8.4% turns" },
  { agent: "OpenClaw", model: "Qwen3.5-397B", domain: "GDPVal", skillMethod: "ReasoningBank", without: 51.7, withSkills: 43.1, cost: "↑ 4.7% turns" },
  { agent: "OpenClaw", model: "Qwen3.5-397B", domain: "GDPVal", skillMethod: "Human Design", without: 51.7, withSkills: 56.9, cost: "↑ 5.1% turns" },
  { agent: "OpenClaw", model: "Qwen3.5-27B", domain: "GDPVal", skillMethod: "Human Design", without: 46.6, withSkills: 48.3, cost: "↓ 13.6% turns" },
  { agent: "OpenClaw", model: "Qwen3.5-397B", domain: "GDPVal", skillMethod: "EvoSkill", without: 51.7, withSkills: 67.2, cost: "↑ 64.9% turns" },
  { agent: "OpenClaw", model: "Qwen3.5-27B", domain: "GDPVal", skillMethod: "EvoSkill", without: 46.6, withSkills: 51.7, cost: "↑ 23.8% turns" },
  { agent: "OpenClaw", model: "Qwen3.5-397B", domain: "GDPVal", skillMethod: "OpenSpace", without: 51.7, withSkills: 67.2, cost: "↑ 51.5% turns" },
  { agent: "OpenClaw", model: "Qwen3.5-27B", domain: "GDPVal", skillMethod: "OpenSpace", without: 46.6, withSkills: 56.9, cost: "↑ 43.8% turns" },
  { agent: "OpenClaw", model: "Qwen3.5-397B", domain: "LiveCodeBench", skillMethod: "EverOS", without: 43.6, withSkills: 48.7, cost: "↓ 10.2% turns" },
  { agent: "OpenClaw", model: "Qwen3.5-27B", domain: "LiveCodeBench", skillMethod: "EverOS", without: 25.6, withSkills: 48.7, cost: "↓ 16.5% turns" },
  { agent: "OpenClaw", model: "Qwen3.5-397B", domain: "LiveCodeBench", skillMethod: "Memento", without: 43.6, withSkills: 60.5, cost: "↑ 21.4% turns" },
  { agent: "OpenClaw", model: "Qwen3.5-27B", domain: "LiveCodeBench", skillMethod: "Memento", without: 25.6, withSkills: 52.6, cost: "↑ 19.8% turns" },
  { agent: "OpenClaw", model: "Qwen3.5-397B", domain: "LiveCodeBench", skillMethod: "ReasoningBank", without: 43.6, withSkills: 59, cost: "↑ 35.0% turns" },
  { agent: "OpenClaw", model: "Qwen3.5-397B", domain: "LiveCodeBench", skillMethod: "Human Design", without: 43.6, withSkills: 61.5, cost: "↑ 6.1% turns" },
  { agent: "OpenClaw", model: "Qwen3.5-27B", domain: "LiveCodeBench", skillMethod: "Human Design", without: 25.6, withSkills: 51.3, cost: "↓ 29.4% turns" },
  { agent: "OpenClaw", model: "Qwen3.5-27B", domain: "BrowseCompPlus", skillMethod: "ReasoningBank", without: 10.8, withSkills: 15.4, cost: "↓ 7.1% turns" },
  { agent: "OpenClaw", model: "Qwen3.5-27B", domain: "BrowseCompPlus", skillMethod: "GEPA", without: 10.8, withSkills: 10.8, cost: "↓ 1.3% turns" },
  { agent: "OpenClaw", model: "Qwen3.5-27B", domain: "SWE-Bench", skillMethod: "ReasoningBank", without: 42.3, withSkills: 57.7, cost: "↑ 8.4% turns" },
  { agent: "OpenClaw", model: "Qwen3.5-27B", domain: "SWE-Bench", skillMethod: "GEPA", without: 42.3, withSkills: 32, cost: "↑ 9.2% turns" },
  { agent: "OpenClaw", model: "Qwen3.5-27B", domain: "OmniMath", skillMethod: "ReasoningBank", without: 44, withSkills: 21, cost: "↓ 28.7% chars" },
  { agent: "OpenClaw", model: "Qwen3.5-27B", domain: "OmniMath", skillMethod: "GEPA", without: 44, withSkills: 32, cost: "↓ 37.9% chars" },
  { agent: "OpenClaw", model: "Qwen3.5-27B", domain: "GDPVal", skillMethod: "ReasoningBank", without: 46.6, withSkills: 53.4, cost: "↑ 11.5% turns" },
  { agent: "OpenClaw", model: "Qwen3.5-27B", domain: "GDPVal", skillMethod: "GEPA", without: 46.6, withSkills: 43.1, cost: "↓ 9.7% turns" },
  { agent: "OpenClaw", model: "Qwen3.5-27B", domain: "LiveCodeBench", skillMethod: "ReasoningBank", without: 25.6, withSkills: 53.8, cost: "↓ 2.7% turns" },
  { agent: "OpenClaw", model: "Qwen3.5-27B", domain: "LiveCodeBench", skillMethod: "GEPA", without: 25.6, withSkills: 33.3, cost: "↓ 37.0% turns" },
  { agent: "OpenClaw", model: "Qwen3.5-397B", domain: "BrowseCompPlus", skillMethod: "GEPA", without: 40, withSkills: 41.5, cost: "↓ 17.4% turns" },
  { agent: "OpenClaw", model: "Qwen3.5-397B", domain: "SWE-Bench", skillMethod: "GEPA", without: 34.6, withSkills: 53.8, cost: "↓ 13.0% turns" },
  { agent: "OpenClaw", model: "Qwen3.5-397B", domain: "OmniMath", skillMethod: "GEPA", without: 48, withSkills: 42, cost: "↓ 18.3% chars" },
  { agent: "OpenClaw", model: "Qwen3.5-397B", domain: "GDPVal", skillMethod: "GEPA", without: 51.7, withSkills: 53.4, cost: "↑ 2.7% turns" },
  { agent: "OpenClaw", model: "Qwen3.5-397B", domain: "LiveCodeBench", skillMethod: "GEPA", without: 43.6, withSkills: 51.3, cost: "↓ 33.1% turns" },
  { agent: "Nanobot", model: "Qwen3.5-27B", domain: "BrowseCompPlus", skillMethod: "EverOS", without: 7.7, withSkills: 10.8, cost: "↑ 6.8% turns" },
  { agent: "Nanobot", model: "Qwen3.5-27B", domain: "BrowseCompPlus", skillMethod: "Memento", without: 7.7, withSkills: 13.8, cost: "↑ 3.2% turns" },
  { agent: "Nanobot", model: "Qwen3.5-27B", domain: "BrowseCompPlus", skillMethod: "ReasoningBank", without: 7.7, withSkills: 9.2, cost: "↑ 4.7% turns" },
  { agent: "Nanobot", model: "Qwen3.5-27B", domain: "BrowseCompPlus", skillMethod: "Human Design", without: 7.7, withSkills: 15.4, cost: "↑ 20.1% turns" },
  { agent: "Nanobot", model: "Qwen3.5-27B", domain: "BrowseCompPlus", skillMethod: "GEPA", without: 7.7, withSkills: 10.8, cost: "↓ 6.5% turns" },
  { agent: "Nanobot", model: "Qwen3.5-27B", domain: "SWE-Bench", skillMethod: "EverOS", without: 19.2, withSkills: 23.1, cost: "↓ 2.9% turns" },
  { agent: "Nanobot", model: "Qwen3.5-27B", domain: "SWE-Bench", skillMethod: "Memento", without: 19.2, withSkills: 25, cost: "↑ 0.2% turns" },
  { agent: "Nanobot", model: "Qwen3.5-27B", domain: "SWE-Bench", skillMethod: "ReasoningBank", without: 19.2, withSkills: 19.2, cost: "↑ 7.8% turns" },
  { agent: "Nanobot", model: "Qwen3.5-27B", domain: "SWE-Bench", skillMethod: "Human Design", without: 19.2, withSkills: 30.8, cost: "↑ 9.4% turns" },
  { agent: "Nanobot", model: "Qwen3.5-27B", domain: "SWE-Bench", skillMethod: "GEPA", without: 19.2, withSkills: 23.1, cost: "↑ 8.5% turns" },
  { agent: "Nanobot", model: "Qwen3.5-27B", domain: "OmniMath", skillMethod: "EverOS", without: 47, withSkills: 43, cost: "↑ 2.8% chars" },
  { agent: "Nanobot", model: "Qwen3.5-27B", domain: "OmniMath", skillMethod: "Memento", without: 47, withSkills: 42, cost: "↑ 1843.1% chars" },
  { agent: "Nanobot", model: "Qwen3.5-27B", domain: "OmniMath", skillMethod: "ReasoningBank", without: 47, withSkills: 42, cost: "↑ 42.4% chars" },
  { agent: "Nanobot", model: "Qwen3.5-27B", domain: "OmniMath", skillMethod: "GEPA", without: 47, withSkills: 44, cost: "↓ 0.2% chars" },
  { agent: "Nanobot", model: "Qwen3.5-27B", domain: "GDPVal", skillMethod: "EverOS", without: 48.3, withSkills: 60.3, cost: "↑ 10.9% turns" },
  { agent: "Nanobot", model: "Qwen3.5-27B", domain: "GDPVal", skillMethod: "Memento", without: 48.3, withSkills: 51.7, cost: "↑ 15.1% turns" },
  { agent: "Nanobot", model: "Qwen3.5-27B", domain: "GDPVal", skillMethod: "ReasoningBank", without: 48.3, withSkills: 43.1, cost: "↑ 20.5% turns" },
  { agent: "Nanobot", model: "Qwen3.5-27B", domain: "GDPVal", skillMethod: "Human Design", without: 48.3, withSkills: 55.2, cost: "↑ 16.9% turns" },
  { agent: "Nanobot", model: "Qwen3.5-27B", domain: "GDPVal", skillMethod: "GEPA", without: 48.3, withSkills: 48.3, cost: "↑ 23.2% turns" },
  { agent: "Nanobot", model: "Qwen3.5-27B", domain: "LiveCodeBench", skillMethod: "EverOS", without: 20.5, withSkills: 15.4, cost: "↓ 1.4% turns" },
  { agent: "Nanobot", model: "Qwen3.5-27B", domain: "LiveCodeBench", skillMethod: "Memento", without: 20.5, withSkills: 36.8, cost: "↑ 18.8% turns" },
  { agent: "Nanobot", model: "Qwen3.5-27B", domain: "LiveCodeBench", skillMethod: "ReasoningBank", without: 20.5, withSkills: 33.3, cost: "↑ 15.9% turns" },
  { agent: "Nanobot", model: "Qwen3.5-27B", domain: "LiveCodeBench", skillMethod: "Human Design", without: 20.5, withSkills: 43.6, cost: "↑ 16.7% turns" },
  { agent: "Nanobot", model: "Qwen3.5-27B", domain: "LiveCodeBench", skillMethod: "GEPA", without: 20.5, withSkills: 33.3, cost: "↑ 24.1% turns" },
  { agent: "Nanobot", model: "Qwen3.5-397B", domain: "BrowseCompPlus", skillMethod: "EverOS", without: 13.8, withSkills: 20, cost: "↑ 1.1% turns" },
  { agent: "Nanobot", model: "Qwen3.5-397B", domain: "BrowseCompPlus", skillMethod: "Memento", without: 13.8, withSkills: 20, cost: "↓ 8.4% turns" },
  { agent: "Nanobot", model: "Qwen3.5-397B", domain: "BrowseCompPlus", skillMethod: "ReasoningBank", without: 13.8, withSkills: 20, cost: "↑ 19.6% turns" },
  { agent: "Nanobot", model: "Qwen3.5-397B", domain: "BrowseCompPlus", skillMethod: "Human Design", without: 13.8, withSkills: 21.5, cost: "↑ 18.3% turns" },
  { agent: "Nanobot", model: "Qwen3.5-397B", domain: "BrowseCompPlus", skillMethod: "GEPA", without: 13.8, withSkills: 13.8, cost: "↑ 11.4% turns" },
  { agent: "Nanobot", model: "Qwen3.5-397B", domain: "SWE-Bench", skillMethod: "EverOS", without: 26.9, withSkills: 30.8, cost: "↑ 0.2% turns" },
  { agent: "Nanobot", model: "Qwen3.5-397B", domain: "SWE-Bench", skillMethod: "Memento", without: 26.9, withSkills: 16.7, cost: "↓ 2.0% turns" },
  { agent: "Nanobot", model: "Qwen3.5-397B", domain: "SWE-Bench", skillMethod: "ReasoningBank", without: 26.9, withSkills: 26.9, cost: "↑ 1.9% turns" },
  { agent: "Nanobot", model: "Qwen3.5-397B", domain: "SWE-Bench", skillMethod: "Human Design", without: 26.9, withSkills: 38.5, cost: "↑ 1.9% turns" },
  { agent: "Nanobot", model: "Qwen3.5-397B", domain: "SWE-Bench", skillMethod: "GEPA", without: 26.9, withSkills: 26.9, cost: "↑ 1.9% turns" },
  { agent: "Nanobot", model: "Qwen3.5-397B", domain: "OmniMath", skillMethod: "EverOS", without: 53, withSkills: 51, cost: "↓ 2.8% chars" },
  { agent: "Nanobot", model: "Qwen3.5-397B", domain: "OmniMath", skillMethod: "Memento", without: 53, withSkills: 55, cost: "↑ 1484.9% chars" },
  { agent: "Nanobot", model: "Qwen3.5-397B", domain: "OmniMath", skillMethod: "ReasoningBank", without: 53, withSkills: 49, cost: "↑ 30.0% chars" },
  { agent: "Nanobot", model: "Qwen3.5-397B", domain: "OmniMath", skillMethod: "GEPA", without: 53, withSkills: 55, cost: "↑ 1.9% chars" },
  { agent: "Nanobot", model: "Qwen3.5-397B", domain: "GDPVal", skillMethod: "EverOS", without: 55.2, withSkills: 63.8, cost: "↑ 1.2% turns" },
  { agent: "Nanobot", model: "Qwen3.5-397B", domain: "GDPVal", skillMethod: "Memento", without: 55.2, withSkills: 58.6, cost: "↓ 2.6% turns" },
  { agent: "Nanobot", model: "Qwen3.5-397B", domain: "GDPVal", skillMethod: "ReasoningBank", without: 55.2, withSkills: 51.7, cost: "↓ 0.4% turns" },
  { agent: "Nanobot", model: "Qwen3.5-397B", domain: "GDPVal", skillMethod: "Human Design", without: 55.2, withSkills: 55.2, cost: "↓ 4.3% turns" },
  { agent: "Nanobot", model: "Qwen3.5-397B", domain: "GDPVal", skillMethod: "GEPA", without: 55.2, withSkills: 46.6, cost: "↑ 14.7% turns" },
  { agent: "Nanobot", model: "Qwen3.5-397B", domain: "LiveCodeBench", skillMethod: "EverOS", without: 43.6, withSkills: 25.6, cost: "↑ 4.1% turns" },
  { agent: "Nanobot", model: "Qwen3.5-397B", domain: "LiveCodeBench", skillMethod: "Memento", without: 43.6, withSkills: 50, cost: "↓ 0.8% turns" },
  { agent: "Nanobot", model: "Qwen3.5-397B", domain: "LiveCodeBench", skillMethod: "ReasoningBank", without: 43.6, withSkills: 53.8, cost: "↑ 9.8% turns" },
  { agent: "Nanobot", model: "Qwen3.5-397B", domain: "LiveCodeBench", skillMethod: "Human Design", without: 43.6, withSkills: 38.5, cost: "↑ 20.4% turns" },
  { agent: "Nanobot", model: "Qwen3.5-397B", domain: "LiveCodeBench", skillMethod: "GEPA", without: 43.6, withSkills: 48.7, cost: "↓ 22.9% turns" },
];
