export type Agent = "OpenClaw" | "Nanobot";

export type Domain =
  | "BrowseCompPlus"
  | "SWE-Bench"
  | "LiveCodeBench"
  | "GDPVal";

// SkillMethod is a string so new methods in leaderboard.csv don't require code changes.
export type SkillMethod = string;

export interface LeaderboardEntry {
  agent: Agent;
  model: string;
  domain: Domain;
  skillMethod: SkillMethod;
  vanilla: number;
  methodScore: number;
}

export interface TurnCostEntry {
  agent: Agent;
  model: string;
  skillMethod: SkillMethod;
  all: number;
  solved: number;
  unsolved: number;
}

export const AGENTS: Agent[] = ["OpenClaw", "Nanobot"];

export const DOMAINS: Domain[] = [
  "BrowseCompPlus",
  "LiveCodeBench",
  "SWE-Bench",
  "GDPVal",
];

// Auto-regenerated by scripts/csv-to-data.js from unique skillMethod values in the CSV.
export const SKILL_METHODS: SkillMethod[] = ["Memento", "ReasoningBank", "GEPA", "Anchor Skill†"];

export const AGENT_COLORS: Record<Agent, string> = {
  OpenClaw: "#ef4444",
  Nanobot: "#3b82f6",
};

export const AGENT_BAR_COLORS: Record<Agent, string> = {
  OpenClaw: "#c2703a",
  Nanobot: "#6366f1",
};

export const DOMAIN_LABELS: Record<Domain, string> = {
  BrowseCompPlus: "Web Research",
  "SWE-Bench": "Software Engineering",
  LiveCodeBench: "Algorithmic Reasoning",
  GDPVal: "Knowledge Work",
};

export const DOMAIN_TAG_COLORS: Record<Domain, { bg: string; text: string }> = {
  BrowseCompPlus: { bg: "#fde68a", text: "#78350f" },
  "SWE-Bench": { bg: "#fce7f3", text: "#9d174d" },
  LiveCodeBench: { bg: "#dbeafe", text: "#1e40af" },
  GDPVal: { bg: "#ede9fe", text: "#5b21b6" },
};

// Fallback palette cycles through these colors for any skill method not in the explicit map.
const SKILL_METHOD_PALETTE: Array<{ bg: string; text: string }> = [
  { bg: "#d1fae5", text: "#065f46" },
  { bg: "#e0f2fe", text: "#0369a1" },
  { bg: "#fce7f3", text: "#9d174d" },
  { bg: "#fef3c7", text: "#92400e" },
  { bg: "#ede9fe", text: "#5b21b6" },
  { bg: "#fef9c3", text: "#713f12" },
];

const EXPLICIT_METHOD_COLORS: Record<string, { bg: string; text: string }> = {
  "Anchor Skill†": { bg: "#e0f2fe", text: "#0369a1" },
};

export const SKILL_METHOD_TAG_COLORS: Record<string, { bg: string; text: string }> = new Proxy(
  EXPLICIT_METHOD_COLORS,
  {
    get(target, prop: string) {
      if (prop in target) return target[prop];
      // Deterministic hash-based color for unknown methods.
      let h = 0;
      for (let i = 0; i < prop.length; i++) h = (h * 31 + prop.charCodeAt(i)) >>> 0;
      return SKILL_METHOD_PALETTE[h % SKILL_METHOD_PALETTE.length];
    },
  }
);

// --- Domain descriptions (from README) ---

export interface DomainInfo {
  id: Domain;
  name: string;
  baseBenchmark: string;
  category: string;
  description: string;
  abilities: number;
  communities: number;
  abilitiesPerTask: number;
  train: number;
  test: number;
  docker: boolean;
}

export const DOMAIN_INFO: DomainInfo[] = [
  {
    id: "BrowseCompPlus",
    name: "Web Research",
    baseBenchmark: "BrowseComp-Plus",
    category: "Web Research",
    description: "Search a controlled corpus and verify evidence for multi-constraint questions.",
    abilities: 38,
    communities: 13,
    abilitiesPerTask: 2.42,
    train: 154,
    test: 65,
    docker: false,
  },
  {
    id: "LiveCodeBench",
    name: "Algorithmic Reasoning",
    baseBenchmark: "LiveCodeBench",
    category: "Algorithmic Reasoning",
    description: "Solve programming problems against hidden test cases with pass@1 scoring.",
    abilities: 58,
    communities: 22,
    abilitiesPerTask: 2.12,
    train: 182,
    test: 86,
    docker: false,
  },
  {
    id: "SWE-Bench",
    name: "Software Engineering",
    baseBenchmark: "SWE-Bench Verified",
    category: "Software Engineering",
    description: "Repair real-world repositories and pass the designated hidden test suites.",
    abilities: 38,
    communities: 15,
    abilitiesPerTask: 2.21,
    train: 87,
    test: 56,
    docker: true,
  },
  {
    id: "GDPVal",
    name: "Knowledge Work",
    baseBenchmark: "GDPVal",
    category: "Knowledge Work",
    description: "Produce professional deliverables evaluated against expert references.",
    abilities: 36,
    communities: 6,
    abilitiesPerTask: 2.63,
    train: 105,
    test: 60,
    docker: false,
  },
];

// --- Skill method descriptions ---

export interface AllMethodInfo {
  name: string;
  description: string;
  approach: string;
  github: string;
}

export const ALL_METHODS: AllMethodInfo[] = [
  {
    name: "Memento",
    description: "Retrieves the closest retained training case, using surface similarity to route prior task experience.",
    approach: "Retrieval-based (CBR)",
    github: "https://github.com/Agent-on-the-Fly/Memento",
  },
  {
    name: "ReasoningBank",
    description: "Distills natural-language strategies from training trajectories and retrieves them by strategy similarity.",
    approach: "Memory + reasoning",
    github: "https://github.com/google-research/reasoning-bank",
  },
  {
    name: "GEPA",
    description: "Evolves one prompt on the training split and broadcasts it to every test task without per-task retrieval.",
    approach: "Prompt evolution",
    github: "https://github.com/gepa-ai/gepa",
  },
  {
    name: "Anchor Skill†",
    description: "Diagnostic reference using train-side Ability-grounded skill content and curator-side Ability-label routing. It is not a deployable automatic method.",
    approach: "Diagnostic reference",
    github: "",
  },
];

// --- Turn cost data (Table 4, percentage change in turns vs. Vanilla) ---

export const turnCostData: TurnCostEntry[] = [
  { agent: "OpenClaw", model: "Qwen3.5-27B", skillMethod: "Memento", all: 40.7, solved: 39.4, unsolved: 23.5 },
  { agent: "OpenClaw", model: "Qwen3.5-27B", skillMethod: "ReasoningBank", all: -6.3, solved: -5.7, unsolved: -16.3 },
  { agent: "OpenClaw", model: "Qwen3.5-27B", skillMethod: "GEPA", all: -4.8, solved: 4.4, unsolved: -18.2 },
  { agent: "OpenClaw", model: "Qwen3.5-27B", skillMethod: "Anchor Skill†", all: -3.4, solved: -13.6, unsolved: -2.8 },
  { agent: "Nanobot", model: "Qwen3.5-27B", skillMethod: "Memento", all: -2.1, solved: 4.8, unsolved: -0.9 },
  { agent: "Nanobot", model: "Qwen3.5-27B", skillMethod: "ReasoningBank", all: 3.6, solved: 2.4, unsolved: 7.9 },
  { agent: "Nanobot", model: "Qwen3.5-27B", skillMethod: "GEPA", all: -7.2, solved: 8, unsolved: -13 },
  { agent: "Nanobot", model: "Qwen3.5-27B", skillMethod: "Anchor Skill†", all: -8.8, solved: -10.6, unsolved: -9.8 },
  { agent: "OpenClaw", model: "Qwen3.5-397B", skillMethod: "Memento", all: -3.5, solved: 4.3, unsolved: -18.8 },
  { agent: "OpenClaw", model: "Qwen3.5-397B", skillMethod: "ReasoningBank", all: -10.3, solved: -2.1, unsolved: -26.1 },
  { agent: "OpenClaw", model: "Qwen3.5-397B", skillMethod: "GEPA", all: 25.4, solved: 27.6, unsolved: 13.1 },
  { agent: "OpenClaw", model: "Qwen3.5-397B", skillMethod: "Anchor Skill†", all: -8, solved: -5.4, unsolved: -11.3 },
  { agent: "Nanobot", model: "Qwen3.5-397B", skillMethod: "Memento", all: -10.8, solved: -9.3, unsolved: -20.8 },
  { agent: "Nanobot", model: "Qwen3.5-397B", skillMethod: "ReasoningBank", all: -0.4, solved: 1, unsolved: 4.7 },
  { agent: "Nanobot", model: "Qwen3.5-397B", skillMethod: "GEPA", all: 13.7, solved: 24.4, unsolved: -8.2 },
  { agent: "Nanobot", model: "Qwen3.5-397B", skillMethod: "Anchor Skill†", all: -4, solved: 1.4, unsolved: 8.3 },
  { agent: "OpenClaw", model: "Gemma-4-31B", skillMethod: "Memento", all: 13.6, solved: 38.8, unsolved: 10.4 },
  { agent: "OpenClaw", model: "Gemma-4-31B", skillMethod: "ReasoningBank", all: 34.8, solved: 31.6, unsolved: 42.8 },
  { agent: "OpenClaw", model: "Gemma-4-31B", skillMethod: "GEPA", all: 44.6, solved: 40.3, unsolved: 52.7 },
  { agent: "OpenClaw", model: "Gemma-4-31B", skillMethod: "Anchor Skill†", all: 7.6, solved: 16.5, unsolved: 26.9 },
  { agent: "Nanobot", model: "Gemma-4-31B", skillMethod: "Memento", all: 43.9, solved: 12.8, unsolved: -16 },
  { agent: "Nanobot", model: "Gemma-4-31B", skillMethod: "ReasoningBank", all: 37.6, solved: 30.4, unsolved: 42.4 },
  { agent: "Nanobot", model: "Gemma-4-31B", skillMethod: "GEPA", all: 41.5, solved: 9.3, unsolved: -8.3 },
  { agent: "Nanobot", model: "Gemma-4-31B", skillMethod: "Anchor Skill†", all: 32.7, solved: 11.5, unsolved: -6.4 },
];

// --- Leaderboard data (Table 3 means; standard errors are omitted on the site) ---

export const leaderboardData: LeaderboardEntry[] = [
  { agent: "OpenClaw", model: "Qwen3.5-27B", domain: "BrowseCompPlus", skillMethod: "Memento", vanilla: 10.8, methodScore: 11.3 },
  { agent: "OpenClaw", model: "Qwen3.5-27B", domain: "BrowseCompPlus", skillMethod: "ReasoningBank", vanilla: 10.8, methodScore: 12.8 },
  { agent: "OpenClaw", model: "Qwen3.5-27B", domain: "BrowseCompPlus", skillMethod: "GEPA", vanilla: 10.8, methodScore: 14.9 },
  { agent: "OpenClaw", model: "Qwen3.5-27B", domain: "BrowseCompPlus", skillMethod: "Anchor Skill†", vanilla: 10.8, methodScore: 14.9 },
  { agent: "OpenClaw", model: "Qwen3.5-27B", domain: "LiveCodeBench", skillMethod: "Memento", vanilla: 51.9, methodScore: 53.9 },
  { agent: "OpenClaw", model: "Qwen3.5-27B", domain: "LiveCodeBench", skillMethod: "ReasoningBank", vanilla: 51.9, methodScore: 57.4 },
  { agent: "OpenClaw", model: "Qwen3.5-27B", domain: "LiveCodeBench", skillMethod: "GEPA", vanilla: 51.9, methodScore: 53.9 },
  { agent: "OpenClaw", model: "Qwen3.5-27B", domain: "LiveCodeBench", skillMethod: "Anchor Skill†", vanilla: 51.9, methodScore: 60.5 },
  { agent: "OpenClaw", model: "Qwen3.5-27B", domain: "SWE-Bench", skillMethod: "Memento", vanilla: 42.3, methodScore: 45.2 },
  { agent: "OpenClaw", model: "Qwen3.5-27B", domain: "SWE-Bench", skillMethod: "ReasoningBank", vanilla: 42.3, methodScore: 36.9 },
  { agent: "OpenClaw", model: "Qwen3.5-27B", domain: "SWE-Bench", skillMethod: "GEPA", vanilla: 42.3, methodScore: 41.7 },
  { agent: "OpenClaw", model: "Qwen3.5-27B", domain: "SWE-Bench", skillMethod: "Anchor Skill†", vanilla: 42.3, methodScore: 52.4 },
  { agent: "OpenClaw", model: "Qwen3.5-27B", domain: "GDPVal", skillMethod: "Memento", vanilla: 43.6, methodScore: 44.3 },
  { agent: "OpenClaw", model: "Qwen3.5-27B", domain: "GDPVal", skillMethod: "ReasoningBank", vanilla: 43.6, methodScore: 48.2 },
  { agent: "OpenClaw", model: "Qwen3.5-27B", domain: "GDPVal", skillMethod: "GEPA", vanilla: 43.6, methodScore: 31.3 },
  { agent: "OpenClaw", model: "Qwen3.5-27B", domain: "GDPVal", skillMethod: "Anchor Skill†", vanilla: 43.6, methodScore: 48.6 },
  { agent: "Nanobot", model: "Qwen3.5-27B", domain: "BrowseCompPlus", skillMethod: "Memento", vanilla: 8.7, methodScore: 12.3 },
  { agent: "Nanobot", model: "Qwen3.5-27B", domain: "BrowseCompPlus", skillMethod: "ReasoningBank", vanilla: 8.7, methodScore: 9.2 },
  { agent: "Nanobot", model: "Qwen3.5-27B", domain: "BrowseCompPlus", skillMethod: "GEPA", vanilla: 8.7, methodScore: 11.8 },
  { agent: "Nanobot", model: "Qwen3.5-27B", domain: "BrowseCompPlus", skillMethod: "Anchor Skill†", vanilla: 8.7, methodScore: 13.3 },
  { agent: "Nanobot", model: "Qwen3.5-27B", domain: "LiveCodeBench", skillMethod: "Memento", vanilla: 52.7, methodScore: 57 },
  { agent: "Nanobot", model: "Qwen3.5-27B", domain: "LiveCodeBench", skillMethod: "ReasoningBank", vanilla: 52.7, methodScore: 62.4 },
  { agent: "Nanobot", model: "Qwen3.5-27B", domain: "LiveCodeBench", skillMethod: "GEPA", vanilla: 52.7, methodScore: 60.5 },
  { agent: "Nanobot", model: "Qwen3.5-27B", domain: "LiveCodeBench", skillMethod: "Anchor Skill†", vanilla: 52.7, methodScore: 63.2 },
  { agent: "Nanobot", model: "Qwen3.5-27B", domain: "SWE-Bench", skillMethod: "Memento", vanilla: 45.8, methodScore: 9.5 },
  { agent: "Nanobot", model: "Qwen3.5-27B", domain: "SWE-Bench", skillMethod: "ReasoningBank", vanilla: 45.8, methodScore: 53 },
  { agent: "Nanobot", model: "Qwen3.5-27B", domain: "SWE-Bench", skillMethod: "GEPA", vanilla: 45.8, methodScore: 48.8 },
  { agent: "Nanobot", model: "Qwen3.5-27B", domain: "SWE-Bench", skillMethod: "Anchor Skill†", vanilla: 45.8, methodScore: 49.4 },
  { agent: "Nanobot", model: "Qwen3.5-27B", domain: "GDPVal", skillMethod: "Memento", vanilla: 43.9, methodScore: 47.6 },
  { agent: "Nanobot", model: "Qwen3.5-27B", domain: "GDPVal", skillMethod: "ReasoningBank", vanilla: 43.9, methodScore: 49.2 },
  { agent: "Nanobot", model: "Qwen3.5-27B", domain: "GDPVal", skillMethod: "GEPA", vanilla: 43.9, methodScore: 46.6 },
  { agent: "Nanobot", model: "Qwen3.5-27B", domain: "GDPVal", skillMethod: "Anchor Skill†", vanilla: 43.9, methodScore: 57.7 },
  { agent: "OpenClaw", model: "Qwen3.5-397B", domain: "BrowseCompPlus", skillMethod: "Memento", vanilla: 31.8, methodScore: 33.8 },
  { agent: "OpenClaw", model: "Qwen3.5-397B", domain: "BrowseCompPlus", skillMethod: "ReasoningBank", vanilla: 31.8, methodScore: 39 },
  { agent: "OpenClaw", model: "Qwen3.5-397B", domain: "BrowseCompPlus", skillMethod: "GEPA", vanilla: 31.8, methodScore: 32.3 },
  { agent: "OpenClaw", model: "Qwen3.5-397B", domain: "BrowseCompPlus", skillMethod: "Anchor Skill†", vanilla: 31.8, methodScore: 45.3 },
  { agent: "OpenClaw", model: "Qwen3.5-397B", domain: "LiveCodeBench", skillMethod: "Memento", vanilla: 52.7, methodScore: 60.9 },
  { agent: "OpenClaw", model: "Qwen3.5-397B", domain: "LiveCodeBench", skillMethod: "ReasoningBank", vanilla: 52.7, methodScore: 59.3 },
  { agent: "OpenClaw", model: "Qwen3.5-397B", domain: "LiveCodeBench", skillMethod: "GEPA", vanilla: 52.7, methodScore: 61.6 },
  { agent: "OpenClaw", model: "Qwen3.5-397B", domain: "LiveCodeBench", skillMethod: "Anchor Skill†", vanilla: 52.7, methodScore: 64 },
  { agent: "OpenClaw", model: "Qwen3.5-397B", domain: "SWE-Bench", skillMethod: "Memento", vanilla: 66.7, methodScore: 63.7 },
  { agent: "OpenClaw", model: "Qwen3.5-397B", domain: "SWE-Bench", skillMethod: "ReasoningBank", vanilla: 66.7, methodScore: 61.3 },
  { agent: "OpenClaw", model: "Qwen3.5-397B", domain: "SWE-Bench", skillMethod: "GEPA", vanilla: 66.7, methodScore: 67.9 },
  { agent: "OpenClaw", model: "Qwen3.5-397B", domain: "SWE-Bench", skillMethod: "Anchor Skill†", vanilla: 66.7, methodScore: 76.8 },
  { agent: "OpenClaw", model: "Qwen3.5-397B", domain: "GDPVal", skillMethod: "Memento", vanilla: 55.8, methodScore: 50 },
  { agent: "OpenClaw", model: "Qwen3.5-397B", domain: "GDPVal", skillMethod: "ReasoningBank", vanilla: 55.8, methodScore: 57.3 },
  { agent: "OpenClaw", model: "Qwen3.5-397B", domain: "GDPVal", skillMethod: "GEPA", vanilla: 55.8, methodScore: 56.5 },
  { agent: "OpenClaw", model: "Qwen3.5-397B", domain: "GDPVal", skillMethod: "Anchor Skill†", vanilla: 55.8, methodScore: 59.6 },
  { agent: "Nanobot", model: "Qwen3.5-397B", domain: "BrowseCompPlus", skillMethod: "Memento", vanilla: 12.8, methodScore: 16.9 },
  { agent: "Nanobot", model: "Qwen3.5-397B", domain: "BrowseCompPlus", skillMethod: "ReasoningBank", vanilla: 12.8, methodScore: 15.9 },
  { agent: "Nanobot", model: "Qwen3.5-397B", domain: "BrowseCompPlus", skillMethod: "GEPA", vanilla: 12.8, methodScore: 14.9 },
  { agent: "Nanobot", model: "Qwen3.5-397B", domain: "BrowseCompPlus", skillMethod: "Anchor Skill†", vanilla: 12.8, methodScore: 20 },
  { agent: "Nanobot", model: "Qwen3.5-397B", domain: "LiveCodeBench", skillMethod: "Memento", vanilla: 57.8, methodScore: 63.5 },
  { agent: "Nanobot", model: "Qwen3.5-397B", domain: "LiveCodeBench", skillMethod: "ReasoningBank", vanilla: 57.8, methodScore: 64.3 },
  { agent: "Nanobot", model: "Qwen3.5-397B", domain: "LiveCodeBench", skillMethod: "GEPA", vanilla: 57.8, methodScore: 65.1 },
  { agent: "Nanobot", model: "Qwen3.5-397B", domain: "LiveCodeBench", skillMethod: "Anchor Skill†", vanilla: 57.8, methodScore: 69.8 },
  { agent: "Nanobot", model: "Qwen3.5-397B", domain: "SWE-Bench", skillMethod: "Memento", vanilla: 62.5, methodScore: 64.9 },
  { agent: "Nanobot", model: "Qwen3.5-397B", domain: "SWE-Bench", skillMethod: "ReasoningBank", vanilla: 62.5, methodScore: 63.1 },
  { agent: "Nanobot", model: "Qwen3.5-397B", domain: "SWE-Bench", skillMethod: "GEPA", vanilla: 62.5, methodScore: 71.4 },
  { agent: "Nanobot", model: "Qwen3.5-397B", domain: "SWE-Bench", skillMethod: "Anchor Skill†", vanilla: 62.5, methodScore: 79.8 },
  { agent: "Nanobot", model: "Qwen3.5-397B", domain: "GDPVal", skillMethod: "Memento", vanilla: 53.4, methodScore: 52.2 },
  { agent: "Nanobot", model: "Qwen3.5-397B", domain: "GDPVal", skillMethod: "ReasoningBank", vanilla: 53.4, methodScore: 52.5 },
  { agent: "Nanobot", model: "Qwen3.5-397B", domain: "GDPVal", skillMethod: "GEPA", vanilla: 53.4, methodScore: 52.2 },
  { agent: "Nanobot", model: "Qwen3.5-397B", domain: "GDPVal", skillMethod: "Anchor Skill†", vanilla: 53.4, methodScore: 62 },
  { agent: "OpenClaw", model: "Gemma-4-31B", domain: "BrowseCompPlus", skillMethod: "Memento", vanilla: 13.3, methodScore: 16.4 },
  { agent: "OpenClaw", model: "Gemma-4-31B", domain: "BrowseCompPlus", skillMethod: "ReasoningBank", vanilla: 13.3, methodScore: 13.3 },
  { agent: "OpenClaw", model: "Gemma-4-31B", domain: "BrowseCompPlus", skillMethod: "GEPA", vanilla: 13.3, methodScore: 17.4 },
  { agent: "OpenClaw", model: "Gemma-4-31B", domain: "BrowseCompPlus", skillMethod: "Anchor Skill†", vanilla: 13.3, methodScore: 17.9 },
  { agent: "OpenClaw", model: "Gemma-4-31B", domain: "LiveCodeBench", skillMethod: "Memento", vanilla: 72.1, methodScore: 67.8 },
  { agent: "OpenClaw", model: "Gemma-4-31B", domain: "LiveCodeBench", skillMethod: "ReasoningBank", vanilla: 72.1, methodScore: 61.2 },
  { agent: "OpenClaw", model: "Gemma-4-31B", domain: "LiveCodeBench", skillMethod: "GEPA", vanilla: 72.1, methodScore: 69.8 },
  { agent: "OpenClaw", model: "Gemma-4-31B", domain: "LiveCodeBench", skillMethod: "Anchor Skill†", vanilla: 72.1, methodScore: 72.5 },
  { agent: "OpenClaw", model: "Gemma-4-31B", domain: "SWE-Bench", skillMethod: "Memento", vanilla: 25, methodScore: 20.2 },
  { agent: "OpenClaw", model: "Gemma-4-31B", domain: "SWE-Bench", skillMethod: "ReasoningBank", vanilla: 25, methodScore: 31.5 },
  { agent: "OpenClaw", model: "Gemma-4-31B", domain: "SWE-Bench", skillMethod: "GEPA", vanilla: 25, methodScore: 42.3 },
  { agent: "OpenClaw", model: "Gemma-4-31B", domain: "SWE-Bench", skillMethod: "Anchor Skill†", vanilla: 25, methodScore: 32.7 },
  { agent: "OpenClaw", model: "Gemma-4-31B", domain: "GDPVal", skillMethod: "Memento", vanilla: 44.1, methodScore: 33.2 },
  { agent: "OpenClaw", model: "Gemma-4-31B", domain: "GDPVal", skillMethod: "ReasoningBank", vanilla: 44.1, methodScore: 42.7 },
  { agent: "OpenClaw", model: "Gemma-4-31B", domain: "GDPVal", skillMethod: "GEPA", vanilla: 44.1, methodScore: 44.8 },
  { agent: "OpenClaw", model: "Gemma-4-31B", domain: "GDPVal", skillMethod: "Anchor Skill†", vanilla: 44.1, methodScore: 54.8 },
  { agent: "Nanobot", model: "Gemma-4-31B", domain: "BrowseCompPlus", skillMethod: "Memento", vanilla: 9.2, methodScore: 10.3 },
  { agent: "Nanobot", model: "Gemma-4-31B", domain: "BrowseCompPlus", skillMethod: "ReasoningBank", vanilla: 9.2, methodScore: 4.6 },
  { agent: "Nanobot", model: "Gemma-4-31B", domain: "BrowseCompPlus", skillMethod: "GEPA", vanilla: 9.2, methodScore: 9.7 },
  { agent: "Nanobot", model: "Gemma-4-31B", domain: "BrowseCompPlus", skillMethod: "Anchor Skill†", vanilla: 9.2, methodScore: 12.3 },
  { agent: "Nanobot", model: "Gemma-4-31B", domain: "LiveCodeBench", skillMethod: "Memento", vanilla: 69, methodScore: 72.4 },
  { agent: "Nanobot", model: "Gemma-4-31B", domain: "LiveCodeBench", skillMethod: "ReasoningBank", vanilla: 69, methodScore: 72.5 },
  { agent: "Nanobot", model: "Gemma-4-31B", domain: "LiveCodeBench", skillMethod: "GEPA", vanilla: 69, methodScore: 70.2 },
  { agent: "Nanobot", model: "Gemma-4-31B", domain: "LiveCodeBench", skillMethod: "Anchor Skill†", vanilla: 69, methodScore: 73.3 },
  { agent: "Nanobot", model: "Gemma-4-31B", domain: "SWE-Bench", skillMethod: "Memento", vanilla: 17.3, methodScore: 21.4 },
  { agent: "Nanobot", model: "Gemma-4-31B", domain: "SWE-Bench", skillMethod: "ReasoningBank", vanilla: 17.3, methodScore: 24.4 },
  { agent: "Nanobot", model: "Gemma-4-31B", domain: "SWE-Bench", skillMethod: "GEPA", vanilla: 17.3, methodScore: 37.5 },
  { agent: "Nanobot", model: "Gemma-4-31B", domain: "SWE-Bench", skillMethod: "Anchor Skill†", vanilla: 17.3, methodScore: 26.8 },
  { agent: "Nanobot", model: "Gemma-4-31B", domain: "GDPVal", skillMethod: "Memento", vanilla: 43.2, methodScore: 46.2 },
  { agent: "Nanobot", model: "Gemma-4-31B", domain: "GDPVal", skillMethod: "ReasoningBank", vanilla: 43.2, methodScore: 46.5 },
  { agent: "Nanobot", model: "Gemma-4-31B", domain: "GDPVal", skillMethod: "GEPA", vanilla: 43.2, methodScore: 47.9 },
  { agent: "Nanobot", model: "Gemma-4-31B", domain: "GDPVal", skillMethod: "Anchor Skill†", vanilla: 43.2, methodScore: 49.3 },
];
